In [1]:
import numpy as np

x_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
x_test = np.array([[ 2.,  0.,  1.]])

# sklearn.preprocessing.StandardScaler

In [4]:
mu = x_train.mean(axis=0).reshape((1,-1))
sigma = x_train.std(axis=0).reshape((1,-1))
print(mu.shape, sigma.shape)

x_train_standard = (x_train - mu) / sigma 
x_test_standard = (x_test - mu) / sigma 
print(x_test_standard)

(1, 3) (1, 3)
[[1.22474487 0.         0.53452248]]


In [5]:
from sklearn.preprocessing import StandardScaler
a = StandardScaler()

x_train_standard = a.fit_transform(x_train)
x_test_standard = a.transform(x_test) 
print(x_test_standard)

[[1.22474487 0.         0.53452248]]


# sklearn.preprocessing.MinMaxScaler

In [6]:
min_ = x_train.min(axis=0).reshape((1,-1))
max_ = x_train.max(axis=0).reshape((1,-1)) 

x_train_minmax = (x_train - min_) / (max_ - min_)
x_test_minmax = (x_test - min_) / (max_ - min_) 
print(x_test_minmax)

[[1.         0.5        0.66666667]]


In [7]:
from sklearn.preprocessing import MinMaxScaler
a = MinMaxScaler()

x_train_minmax = a.fit_transform(x_train)
x_test_minmax = a.transform(x_test) 
print(x_test_minmax)

[[1.         0.5        0.66666667]]


# sklearn.preprocessing.MaxAbsScaler

In [9]:
maxabs_ = np.abs(x_train).max(axis=0).reshape((1,-1)) 

x_train_maxabs = x_train / maxabs_ 
x_test_maxabs = x_test / maxabs_ 
print(x_test_maxabs)

[[1.  0.  0.5]]


In [10]:
from sklearn.preprocessing import MaxAbsScaler
a = MaxAbsScaler()

x_train_maxabs = a.fit_transform(x_train)
x_test_maxabs = a.transform(x_test) 
print(x_test_maxabs)

[[1.  0.  0.5]]
